<a href="https://colab.research.google.com/github/NEHAL1726/Dspy_Experiments/blob/main/Experiment_13_2301644_Notebook_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 1: Data Selection, Cleaning and Wrangling

# 1. Introduction

# Credit Card Fraud Detection
## Data Selection, Cleaning and Wrangling

Name:

Roll No:

Subject:

## 1. Introduction

The Credit Card Fraud Detection dataset is used to identify fraudulent transactions.
This is a classification problem where the target variable indicates whether a transaction is fraud (1) or normal (0).
The dataset is highly imbalanced, making it suitable for real-world machine learning analysis.

In [1]:
import pandas as pd
import numpy as np

## 2. Load Dataset

In [2]:
import pandas as pd
df = pd.read_csv("creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

## 3. Dataset Information

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3973 entries, 0 to 3972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    3973 non-null   int64
 1   V1      3973 non-null   float64
 2   V2      3973 non-null   float64
 3   V3      3973 non-null   float64
 4   V4      3973 non-null   float64
 5   V5      3973 non-null   float64
 6   V6      3973 non-null   float64
 7   V7      3973 non-null   float64
 8   V8      3973 non-null   float64
 9   V9      3973 non-null   float64
 10  V10     3973 non-null   float64
 11  V11     3973 non-null   float64
 12  V12     3973 non-null   float64
 13  V13     3973 non-null   float64
 14  V14     3973 non-null   float64
 15  V15     3973 non-null   float64
 16  V16     3973 non-null   float64
 17  V17     3973 non-null   float64
 18  V18     3973 non-null   float64
 19  V19     3973 non-null   float64
 20  V20     3973 non-null   float64
 21  V21     3973 non-null   float64
 22  V22     3973 non-null   float64
 23  V23     3972 non-null   float64
 24  V24     3972 non-null   float64
 25  V25     3972 non-null   float64
 26  V26     3972 non-null   float64
 27  V27     3972 non-null   float64
 28  V28     3972 non-null   float64
 29  Amount  3972 non-null   float64
 30  Class   3972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 962.3 KB

## 4. Attribute Description

- Time: Time of transaction  
- Amount: Transaction amount  
- V1–V28: PCA transformed anonymized features  
- Class: Target variable (0 = Normal, 1 = Fraud)

## 5. Check Missing Values

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

Observation:
There are no missing values in the dataset.

## 6. Check Duplicates

In [5]:
df.duplicated().sum()
df = df.drop_duplicates()

## 7. Class Distribution

In [6]:
df['Class'].value_counts()

Class
0.0    3938
1.0       2
Name: count, dtype: int64

Observation:
The dataset is highly imbalanced with very few fraud cases compared to normal transactions.

In [7]:
df = df.drop(['Time'], axis=1)

Reason:
The Time feature is not very useful for fraud detection, so it is removed.